site_name: "DI: Python Dependency Injection"
site_description: Simple pythonic dependency injection
site_url: https://www.adriangb.com/di

theme:
  name: 'material'
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

repo_name: adriangb/di
repo_url: https://github.com/adriangb/di
edit_uri: "blob/main/docs/"

nav:
  - Intro: 'README.md'
  - Scopes: 'scopes.md'
  - Binds: 'binds.md'
  - Wiring: 'wiring.md'
  - Sharing: 'sharing.md'
  - Dependants: 'dependants.md'
  - Solving: 'solving.md'
  - Integrations: 'integrations.md'
  - Contributing: 'contributing.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets

extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true   # set to false to leave out the version selector
  - search:
